# Stage 1 - Build the application
FROM gradle:jdk17 AS build

WORKDIR /app

EXPOSE 9090

ENV GRADLE_USER_HOME /home/gradle/project

COPY . .

# Build the application
RUN ./gradlew clean build --no-daemon

# Stage 2 - Package the application
FROM gradle:jdk17

WORKDIR /app

# Copy the build files from the previous stage for production
# COPY --from=build /app/build/libs/*.jar app.jar

# Copy the build files from the host to the container for development
COPY build/libs/*.jar app.jar

RUN apt-get update && apt-get install -y ca-certificates
ENV DOCKER_ENVIRONMENT=true

EXPOSE 9090

ENTRYPOINT ["java", "-jar", "app.jar"]
